function(moonlight_patch_usbipdcpp source_dir output_source output_include)
    set(patched_root "${CMAKE_CURRENT_BINARY_DIR}/usbipdcpp-moonlight")
    set(patched_include "${patched_root}/include/usbipdcpp")
    file(MAKE_DIRECTORY "${patched_include}")

    file(READ "${source_dir}/include/usbipdcpp/Server.h" server_header)
    set(header_marker "    Server() = default;\n")
    set(header_replacement "${header_marker}    void set_connection_filter(std::function<bool(const asio::ip::tcp::endpoint &)> filter) {\n        connection_filter = std::move(filter);\n    }\n")
    string(REPLACE "${header_marker}" "${header_replacement}" patched_header "${server_header}")
    set(member_marker "    ServerNetworkConfig network_config;\n")
    set(member_replacement "${member_marker}    std::function<bool(const asio::ip::tcp::endpoint &)> connection_filter;\n")
    string(REPLACE "${member_marker}" "${member_replacement}" patched_header "${patched_header}")
    if(patched_header STREQUAL server_header)
        message(FATAL_ERROR "Pinned usbipdcpp Server.h no longer matches the connection-filter patch")
    endif()
    file(WRITE "${patched_include}/Server.h" "${patched_header}")

    file(READ "${source_dir}/src/Server.cpp" server_source)
    set(source_marker "            auto remote_endpoint_name = std::format(\"{}:{}\", remote_endpoint.address().to_string(),\n                                                    remote_endpoint.port());\n")
    set(source_replacement "            if (connection_filter && !connection_filter(remote_endpoint)) {\n                SPDLOG_WARN(\"Rejected unauthorized local USB/IP connection\");\n                continue;\n            }\n${source_marker}")
    string(REPLACE "${source_marker}" "${source_replacement}" patched_source "${server_source}")
    if(patched_source STREQUAL server_source)
        message(FATAL_ERROR "Pinned usbipdcpp Server.cpp no longer matches the connection-filter patch")
    endif()
    file(WRITE "${patched_root}/Server.cpp" "${patched_source}")

    set(${output_source} "${patched_root}/Server.cpp" PARENT_SCOPE)
    set(${output_include} "${patched_root}/include" PARENT_SCOPE)
endfunction()
